ipax77/dsstats

src/pax.dsstats.dbng/Services/FireMmrService.cs
src/sc2dsstats.maui/Services/UploadService.cs

LocalHost Correction & FireMMRService bug fixes

26_10_2022

---

src/pax.dsstats.dbng/Services/FireMmrService.cs

test-branch

---

src/MysqlMigrations/Migrations/20221101211435_LeaverAndNotUploadCounts.Designer.cs
src/MysqlMigrations/Migrations/20221101211435_LeaverAndNotUploadCounts.cs
src/SqliteMigrations/Migrations/20221101211140_LeaverAndNotUploadCounts.Designer.cs
src/SqliteMigrations/Migrations/20221101211140_LeaverAndNotUploadCounts.cs
src/SqliteMigrations/Migrations/ReplayContextModelSnapshot.cs
src/pax.dsstats.dbng/Replay.cs
src/pax.dsstats.dbng/Services/FireMmrService.cs
src/pax.dsstats.shared/ReplayDsRDto.cs

- Leaver - Migration
- NotUpload - Migration

Leaver - Migration

---

src/pax.dsstats.dbng/Services/FireMmrService.cs
src/pax.dsstats.shared/ReplayDsRDto.cs
src/sc2dsstats.maui/Services/UploadService.cs

MmrChange - Calculation & Implementation

Pr mmr change

---

src/pax.dsstats.dbng/CommanderMmr.cs
src/pax.dsstats.dbng/Services/FireMmrService.cs
src/pax.dsstats.dbng/Services/MmrService/MmrService.Cmdr.cs

Habe zuerst auf Basis meines alten Services die Get- & Set-Funktion angepasst und danach die von uns gebastelte Get-Funktion im neuen MmrService.Cmdr angepasst.

CommanderMmr Refactoring (old & new)

---

src/pax.dsstats.dbng/Services/MmrService/MmrService.cs

- eloK increased
- useFactorToTeamMates = false

eloKChangeAndUseFactorChange

---

src/pax.dsstats.dbng/Services/MmrService/MmrService.Cmdr.cs
src/pax.dsstats.dbng/Services/MmrService/MmrService.Std.cs
src/pax.dsstats.dbng/Services/MmrService/MmrService.cs

hatte da noch nen "kleinen" Fehler drin..

ConfidenceImportantHotfix

---

src/pax.dsstats.dbng/Services/MmrService/MmrService.Cmdr.cs
src/pax.dsstats.dbng/Services/MmrService/MmrService.Std.cs
src/pax.dsstats.dbng/Services/MmrService/MmrService.cs
src/pax.dsstats.dbng/Services/MmrService/ReplayProcessData.cs

ConfidenceHotfix3

---

src/pax.dsstats.dbng/Services/MmrService/MmrService.Cmdr.cs
src/pax.dsstats.dbng/Services/MmrService/MmrService.Continue.cs
src/pax.dsstats.dbng/Services/MmrService/MmrService.Progress.cs
src/pax.dsstats.dbng/Services/MmrService/MmrService.Std.cs
src/pax.dsstats.dbng/Services/MmrService/MmrService.cs
src/pax.dsstats.dbng/Services/MmrService/ReplayProcessData.cs

Noch ein paar Verbesserungen in punkto Kompatibilität, für das baldige Refactoring.

MmrServiceDataStructureImprovements

---

src/pax.dsstats.web/dsstats.raven/RatingRepository.Memory.cs

Fix Rating Sort Order #72

---

src/pax.dsstats.dbng/Services/Stats/StatsService.Timeline.cs
src/pax.dsstats.web/Server/Program.cs
src/sc2dsstats.razorlib/Stats/StatsRequestComponent.razor

Handle Multiselect on GameMode Change

---

src/dsstats.mmr/MmrService.cs
src/pax.dsstats.shared/MmrOptions.cs

MmrAdaptions

---

src/dsstats.maui.tests/LeaverHandlingTests.cs
src/dsstats.mmr/MmrService.Calc.cs
src/dsstats.mmr/MmrService.cs
src/dsstats.mmr/ProcessData/PlayerData.cs
src/dsstats.mmr/ProcessData/ReplayData.cs
src/pax.dsstats.dbng/AutoMapperProfile.cs

- Leaver-handling
- LeaverType
- LeaverImpact
- Tests:
- NoLeavers (succesfull)
- OneLeaver (succesfull)
- TwoLeaversSameTeam (succesfull)
(@ipax77 i did the most important tests very carefully and clean. They all work perfectly and are compatible for future continuation. i won't have time this week anymore, so if u wanna write the remaining tests (alot is copy paste and adapt), you can do that. but i am sure of the functionality like it is right now and i believe that we can bring it live like this. have a nice week!)

Leaver handling

---

src/dsstats.maui.tests/LeaverHandlingTests.cs

Fix LeaverHandling Tests

---

src/dsstats.cli/DbToJson.cs
src/dsstats.cli/Program.cs
src/dsstats.cli/dsstats.cli.csproj

Those are the preperations for switching to the new extern project:
- Exclude MmrServiceTests from CLI
- Create DbToJson CLI-Service being able to convert the whole MySql-Db to a Json file given the file-name/-path.
@ipax77 pls merge so we both have a clean state before i start the new project.
(No changes done in the production, only cli-repo!)

Mmr tests preperations

---

src/dsstats.cli/MmrService/MmrService.cs
src/dsstats.mmr/MmrService.Calc.cs
src/dsstats.mmr/MmrService.Cmdr.cs
src/dsstats.mmr/MmrService.ProcessData.cs
src/dsstats.mmr/MmrService.cs
src/dsstats.mmr/ProcessData/PlayerData.cs
src/dsstats.mmr/ProcessData/ReplayData.cs
src/pax.dsstats.dbng/Services/MmrProduce/MmrProduceService.cs

- ReplayData.IsInvalid bugfix
- AddPlayersRankings() cu

Bug fixes and cu

---

src/dsstats.mmr/Maths/GaussianElo.cs
src/dsstats.mmr/MmrService.Calc.cs
src/dsstats.mmr/MmrService.Formulas.cs
src/dsstats.mmr/MmrService.ProcessData.cs
src/pax.dsstats.shared/MmrOptions.cs

fix a crussial bug with the time decay and some clean up to improve readability

Elo correction

---

src/dsstats.razorlib/Builds/BuildsComponent.razor
src/dsstats.razorlib/Replays/ReplayComponent.razor

build bp toggles with own id. fixes #392

---

src/dsstats.wasm/wwwroot/index.html
src/dsstats.web/dsstats.web/Components/App.razor

Fix Build replay breakpoint change

---

src/dsstats.api/Program.cs
src/dsstats.web/dsstats.web.Client/Program.cs
src/dsstats.web/dsstats.web/Program.cs

https not required when running in a docker container

disable https redirect

---

src/dsstats.wasm/Pages/Stats/WinratePage.razor
src/dsstats.web/dsstats.web.Client/Pages/Stats/WinratePage.razor

stats winrate as default stats page

---

src/dsstats.api/Controllers/ReplaysController.cs
src/dsstats.razorlib/Players/Profile/ProfileComponent.razor.cs
src/dsstats.razorlib/Replays/ArcadeReplayComponent.razor
src/dsstats.razorlib/Replays/ReplayComponent.razor
src/dsstats.razorlib/Replays/ReplaysComponent.razor
src/dsstats.razorlib/Replays/ReplaysRequestComponent.razor
src/dsstats.shared/ReplaysRequest.cs

Fix Replays Link from player profile

---

src/MysqlMigrations/Migrations/20241108183146_QueenStats.Designer.cs
src/MysqlMigrations/Migrations/20241108183146_QueenStats.cs

https://github.com/ipax77/dsstats/issues/520

Update DsUnit Queen Weapon Acid Spines #520
